trigger:
- master

pool:
  vmImage: windows-latest

steps:
- checkout: self
  submodules: true
  path: 'UnityWebBrowserSource'
- checkout: git://UnityWebBrowser/UnityWebBrowser
  submodules: true
  path: 'UnityWebBrowserPackage'

- task: CmdLine@2
  displayName: Download CEF
  inputs:
    script: 'pwsh download-cef-binaries.ps1'
    workingDirectory: '..\UnityWebBrowserSource\scripts'

