trigger:
- master

pool:
  vmImage: windows-latest

steps:
- checkout: self
  submodules: true
  path: 'UnityWebBrowserSource'
- checkout: git://UnityWebBrowser/UnityWebBrowser
  submodules: true
  path: 'UnityWebBrowserPackage'

- task: CmdLine@2
  displayName: Download CEF
  inputs:
    script: 'pwsh download-cef-binaries.ps1'
    workingDirectory: '..\UnityWebBrowserSource\scripts'

- task: CmdLine@2
  displayName: Build CEF Process and deploy
  inputs:
    script: 'pwsh publish-browserprocess-and-copy-win64.ps11'
    workingDirectory: '..\UnityWebBrowserSource\scripts'
    
- task: CopyFiles@2
  displayName: Copy files to package repo
  inputs:
    sourceFolder: ..\UnityWebBrowserSource\src\CefBrowser
    contents: '**' 
    targetFolder: ..\UnityWebBrowserPackage
    cleanTargetFolder: true
    overWrite: true
