trigger:
- master

pool:
  vmImage: windows-latest

steps:
- checkout: self
- checkout: git://UnityWebBrowser/UnityWebBrowser

- task: CmdLine@2
  displayName: Download CEF
  inputs:
    script: 'pwsh download-cef-binaries.ps1'
    workingDirectory: UnityWebBrowser/scripts/

