blank_issues_enabled: true
contact_links:
  - name: UWB Project Discussions
    url: https://github.com/Voltstro-Studios/UnityWebBrowser/discussions
    about: Please use this project's discussions to ask and answer questions
