name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # In Azure DevOps they have 'templates', where you could define your tasks to share in a seperate yml file,
  # however, GitHub actions doesn't seem to have that, so it makes maintaining this shit.
  
  build-windows:
    name: 'Windows Build'
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        lfs: false
        path: 'UnityWebBrowserSource/'
        
    - name: Download CEF
      shell: pwsh
      run: '& ./download-cef-binaries-windows-x64.ps1'
      working-directory: UnityWebBrowserSource/scripts/
      
    - name: Build CefBrowserProcess
      shell: pwsh
      run: '& ./publish-browserprocess-win64.ps1'
      working-directory: UnityWebBrowserSource/scripts/
      
    - uses: actions/upload-artifact@v2.2.3
      name: Upload Build
      with:
        name: Windows-CefBrowserProcess
        path: UnityWebBrowserSource/src/CefBrowserProcess/bin/Release/win-x64/publish/
      
  build-linux:
    name: 'Linux Build'
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        lfs: false
        path: 'UnityWebBrowserSource/'
        
    - name: Download CEF
      shell: pwsh
      run: '& ./download-cef-binaries-linux-x64.ps1'
      working-directory: UnityWebBrowserSource/scripts/
      
    - name: Build CefBrowserProcess
      shell: pwsh
      run: '& ./publish-browserprocess-linux64.ps1'
      working-directory: UnityWebBrowserSource/scripts/
    
    - uses: actions/upload-artifact@v2.2.3
      name: Upload Build
      with:
        name: Linux-CefBrowserProcess
        path: UnityWebBrowserSource/src/CefBrowserProcess/bin/Release/linux-x64/publish/
      
  upload-package:
    name: 'Upload Package'
    runs-on: ubuntu-20.04
    needs: [build-windows, build-linux]
    
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout Source'
      with:
        submodules: 'recursive'
        lfs: false
        path: 'UnityWebBrowserSource/'
    
    - uses: shimataro/ssh-key-action@v2
      name: 'Install SSH Key'
      with:
        name: Unity-Package
        key: ${{ secrets.UNITY_PACKAGE_KEY }}
        known_hosts: 'gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf'
        config: |
          Host gitlab.com
            PreferredAuthentications publickey
            IdentityFile ~/.ssh/Unity-Package
            
    - uses: actions/download-artifact@v2
      with:
        path: .
        
    - name: Setup and Release
      shell: pwsh
      run: '& ./UnityWebBrowserSource/.github/workflows/upload-build.ps1'
