name: Build

on:
  push:
    branches: [ master ]

jobs:
  # In Azure DevOps they have 'templates', where you could define your tasks to share in a seperate yml file,
  # however, GitHub actions doesn't seem to have that, so it makes maintaining this shit.
  
  build:
    name: 'Build'
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        lfs: false
        path: 'UnityWebBrowserSource/'

    #Setup the Environment
    - uses: actions/setup-dotnet@v2
      name: Setup .NET
      with:
        dotnet-version: '6.0.x'

    #Node modules cache for the UnityWebBrowser.Pages project
    - name: Pages Cache
      uses: actions/cache@v3.0.7
      with:
        path: UnityWebBrowserSource/src/UnityWebBrowser.Pages/node_modules
        key: Cache-Pages

    #Build pages project
    - name: Build Pages
      shell: pwsh
      run: '& ./build-pages.ps1'
      working-directory: UnityWebBrowserSource/src/DevScripts/
        
    #Build everything that is outside of Unity
    - name: Build Externals
      shell: pwsh
      run: '& ./setup-all.ps1'
      working-directory: UnityWebBrowserSource/src/

    #Unity's cache
    - name: Unity Cache
      uses: actions/cache@v3.0.7
      with:
        path: UnityWebBrowserSource/src/UnityWebBrowser.UnityProject/Library
        key: Cache-Unity

    - name: Build Unity
      uses: game-ci/unity-builder@v2.1.0
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      with:
        projectPath: 'UnityWebBrowserSource/src/UnityWebBrowser.UnityProject/'
        targetPlatform: StandaloneLinux64
        buildsPath: 'UnityWebBrowserSource/src/UnityWebBrowser.UnityProject/Builds'
        versioning: Tag
        androidVersionCode: 1 #This is here so we can stop getting warnings about it, even tho we have no plans to support Android