name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    name: 'Windows Build'
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        lfs: false
        path: 'UnityWebBrowserSource/'
        
    - name: Download CEF
      shell: pwsh
      run: '& download-cef-binaries-windows-x64.ps1'
      working-directory: UnityWebBrowserSource/scripts/
      
    - name: Build CefBrowserProcess
      shell: pwsh
      run: '& publish-browserprocess-win64.ps1'
      working-directory: UnityWebBrowserSource/scripts/
