name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        lfs: false
        path: 'UnityWebBrowserSource/'
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: UnityWebBrowserSource/src/CefBrowserProcess/
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: UnityWebBrowserSource/src/CefBrowserProcess/
