name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # In Azure DevOps they have 'templates', where you could define your tasks to share in a seperate yml file,
  # however, GitHub actions doesn't seem to have that, so it makes maintaining this shit.
  
  build-windows:
    name: 'Windows Build'
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        lfs: false
        path: 'UnityWebBrowserSource/'
        
    - name: Download CEF
      shell: pwsh
      run: '& ./download-cef-binaries-windows-x64.ps1'
      working-directory: UnityWebBrowserSource/scripts/
      
    - name: Build CefBrowserProcess
      shell: pwsh
      run: '& ./publish-browserprocess-win64.ps1'
      working-directory: UnityWebBrowserSource/scripts/
      
  build-linux:
    name: 'Linux Build'
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        lfs: false
        path: 'UnityWebBrowserSource/'
        
    - name: Download CEF
      shell: pwsh
      run: '& ./download-cef-binaries-linux-x64.ps1'
      working-directory: UnityWebBrowserSource/scripts/
      
    - name: Build CefBrowserProcess
      shell: pwsh
      run: '& ./publish-browserprocess-linux64.ps1'
      working-directory: UnityWebBrowserSource/scripts/

  upload-package:
    name: 'Upload Package'
    runs-on: ubuntu-20.04
    needs: [build-windows, build-linux]
    
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout Source'
      with:
        submodules: 'recursive'
        lfs: false
        path: 'UnityWebBrowserSource/'
        
    - uses: actions/checkout@v2
      name: 'Checkout Package'
      with:
        repository: 'https://gitlab.com/Voltstro-Studios/WebBrowser/Package.git'
        lfs: false
        path: 'UnityWebBrowserPackage/'
        token: ${{ secrets.UNITY_PACKAGE_TOKEN }}
