name: Build

on:
  push:
    branches: [ master ]

jobs:
  # In Azure DevOps they have 'templates', where you could define your tasks to share in a seperate yml file,
  # however, GitHub actions doesn't seem to have that, so it makes maintaining this shit.
  
  build:
    name: 'Build'
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        lfs: false
        path: 'UnityWebBrowserSource/'

    # Setup the Environment
    - uses: actions/setup-dotnet@v1
      name: Setup .NET
      with:
        dotnet-version: '6.0.x'

    - name: Pages Cache
      uses: actions/cache@v2.1.6
      with:
        path: UnityWebBrowserSource/src/UnityWebBrowser.Pages/node_modules
        key: Node-Cache
        
    - name: Setup Environment
      shell: pwsh
      run: '& ./setup-all.ps1'
      working-directory: UnityWebBrowserSource/src/

    # Build the base projects  
    - name: Build Base Projects
      shell: pwsh
      run: '& ./publish-all.ps1'
      working-directory: UnityWebBrowserSource/src/DevScripts/

    # Build Unity
    - name: Unity Cache
      uses: actions/cache@v2.1.6
      with:
        path: UnityWebBrowserSource/src/UnityWebBrowser.UnityProject/Library
        key: Library-Cache

    - name: Unity Build
      uses: game-ci/unity-builder@v2.0-alpha-14
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      with:
        projectPath: 'UnityWebBrowserSource/src/UnityWebBrowser.UnityProject/'
        targetPlatform: StandaloneWindows64
        buildsPath: 'UnityWebBrowserSource/src/UnityWebBrowser.UnityProject/Builds'
        versioning: Tag
        androidVersionCode: 1 #This is here so we can stop getting warnings about it, even tho we have no plans to support Android