name: Build

on:
  push

jobs:
  #This job builds the Unity project
  build-unity:
    name: 'Build-Unity'
    runs-on: ubuntu-20.04
    steps:

    #Restore
    - uses: actions/checkout@v2
      with:
        lfs: false
        path: 'UnityWebBrowserSource/'

    #Setup the Environment
    - uses: actions/setup-dotnet@v2
      name: Setup .NET
      with:
        dotnet-version: '6.0.x'

    #Build shared
    - name: Build Shared
      shell: pwsh
      run: '& ./publish-shared.ps1'
      working-directory: UnityWebBrowserSource/src/DevScripts/
        
    #Restore Unity's cache
    - name: Unity Cache
      uses: actions/cache@v3
      with:
        path: UnityWebBrowserSource/src/UnityWebBrowser.UnityProject/Library
        key: Cache-Unity

    #Build the Unity project
    - name: Build Unity
      uses: game-ci/unity-builder@v2.1.0
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      with:
        projectPath: 'UnityWebBrowserSource/src/UnityWebBrowser.UnityProject/'
        targetPlatform: StandaloneLinux64
        buildsPath: 'UnityWebBrowserSource/src/UnityWebBrowser.UnityProject/Builds'
        versioning: Tag
        androidVersionCode: 1 #This is here so we can stop getting warnings about it, even tho we have no plans to support Android

  # Builds the 'Pages' project
  build-pages:
    name: 'Build-Pages'
      runs-on: ubuntu-20.04
      steps:

      #Checkout
      - uses: actions/checkout@v2
        with:
          lfs: false
          path: 'UnityWebBrowserSource/'

      #Restore the cache for pages
      - name: Pages Cache
        uses: actions/cache@v3
        with:
          path: UnityWebBrowserSource/src/UnityWebBrowser.Pages/node_modules
          key: Cache-Pages

      #Build Pages
      - name: Build Pages
        shell: pwsh
        run: '& ./build-pages.ps1'
        working-directory: UnityWebBrowserSource/src/DevScripts/
